import { Locator } from "playwright/test";  
import { LocatorUtils } from "../utils/locatorUtils";
import { start } from "node:repl";
export const sessionManagementLocators = {
    eventmanagmentMenu: LocatorUtils.containsTextIn('h6', 'Event Management'),
    sessionManagementMenu : LocatorUtils.containsTextIn('h6', 'Session Management'),
    ManageHallsButton : LocatorUtils.containsTextIn('button', 'Manage halls'),
    addNewHallButton : LocatorUtils.containsTextIn('button', 'Add new hall'),
    hallNameInput : LocatorUtils.byAttribute('input', 'name', 'hallName'),
    hallLocationInput : LocatorUtils.byAttribute('input', 'name', 'hallLocation'),
    createHallButton : LocatorUtils.containsTextIn('button', 'Create hall'),
    backtoSessionManagementButton : LocatorUtils.containsTextIn('button', 'Back to session management'),
    manageTracksButton : LocatorUtils.containsTextIn('button', 'Manage tracks'),
    addNewTrackButton : LocatorUtils.containsTextIn('button', 'Add new track'),
    trackNameInput : LocatorUtils.byAttribute('input', 'name', 'trackName'),
    colourcodeInput : LocatorUtils.byAttribute('input', 'name', 'colourCode'),
    createTrackButton : LocatorUtils.containsTextIn('button', 'Create track'),
    addsessionButton : LocatorUtils.containsTextIn('button', 'Add session'),
    sessionNameInput : LocatorUtils.byAttribute('input', 'name', 'sessionName'),
    sessionDate : LocatorUtils.byAttribute('input', 'name', 'sessionDate'),
    startTimeInput : LocatorUtils.byAttribute('input', 'name', 'startTime'),
    endTimeInput : LocatorUtils.byAttribute('input', 'name', 'endTime'),
    halldropdown : LocatorUtils.byAttribute('select', 'name', 'hall'),
    selectHallOption : LocatorUtils.byAttribute('option', 'value', 'hall1'),
    trackdropdown : LocatorUtils.byAttribute('select', 'name', 'track'),
    selectTrackOption : LocatorUtils.byAttribute('option', 'value', 'track1'),
    tagsInput : LocatorUtils.byAttribute('input', 'name', 'tags'),
    sessiondescriptionInput : LocatorUtils.byAttribute('textarea', 'name', 'sessionDescription'),
    linkspeakers : LocatorUtils.byAttribute('input', 'name', 'speakers'),
    selectspeakerOption : LocatorUtils.byAttribute('option', 'value', 'speaker1'),
    linkmoderators : LocatorUtils.byAttribute('input', 'name', 'moderators'),
    selectmoderatorOption : LocatorUtils.byAttribute('option', 'value', 'moderator1'),
    POCnameInput : LocatorUtils.byAttribute('input', 'name', 'pocName'),
    POCDesignationInput : LocatorUtils.byAttribute('input', 'name', 'pocDesignation'),
    POCEmailInput : LocatorUtils.byAttribute('input', 'name', 'pocEmail'),
    POCMobileInput : LocatorUtils.byAttribute('input', 'name', 'pocMobile'),
    selectPublishedOption : LocatorUtils.byAttribute('option', 'value', 'published'),
    selectDraftOption : LocatorUtils.byAttribute('option', 'value', 'draft'),
    createSessionButton : LocatorUtils.containsTextIn('button', 'Create session'),
}